---
- hosts: all
  remote_user: tomswiggers
  become_method: sudo
  tasks:
    - name: Ping the node
      ping:
    - name: Install packages
      pacman:
        name: git, vim
        state: latest

