---
- hosts: all
  become: yes
  tasks:
    - name: Ping the node
      ping:
    - name: Install packages
      pacman:
        name: git, tig, vim, dialog, chromium, firefox
        state: latest
    - name: vimrc file 
      copy:
        src: dotfiles/.vimrc 
        dest: /home/tomswiggers/.vimrc
        owner: tomswiggers
        group: tomswiggers

