---
- hosts: all
  become: yes
  tasks:
    - name: Ping the node
      ping:
    - name: Install packages
      pacman:
        name: docker, rkt
        state: latest
    - name: add rkt group
      group:
        name: rkt
        state: present
    - name: Add user to group
      user:
        name: tomswiggers
        groups: docker, rkt
        append: yes
    

