---
- hosts: all
  become: yes
  tasks:
    - name: Ping the node
      ping:
    - name: Install packages
      pacman:
        name: dmenu
        state: latest
    - name: Copy 
      copy:
        src: dotfiles/config/sway/config
        dest: /home/tomswiggers/.config/sway/config
        owner: tomswiggers
        group: tomswiggers
    

        #sway
        #curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/swaylock-git.tar.gz
