---
- hosts: all
  remote_user: tomswiggers
  become_method: sudo
  tasks:
    - name: Ping the node
      ping:
    - name: Install urxvt
      pacman:
        name: rxvt-unicode
        state: latest
    - name: Copy 
      copy:
        src: dotfiles/.Xresources 
        dest: ~/.Xresources
     - name: Copy 
      copy:
        src: dotfiles/.urxvt/ext/font-size 
        dest: ~/.urxvt/ext/font-size
    

