---
- hosts: all
  become: yes
  tasks:
    - name: Ping the node
      ping:
    - name: Install urxvt
      pacman:
        name: rxvt-unicode
        state: latest
    - name: Copy 
      copy:
        src: dotfiles/.Xdefaults 
        dest: /home/tomswiggers/.Xdefaults
    - name: Copy 
      copy:
        src: dotfiles/.urxvt/ext/font-size 
        dest: /home/tomswiggers/.urxvt/ext/font-size
    

