---
- hosts: all
  become: yes
  tasks:
    - name: Ping the node
      ping:
    - name: Install packages
      pacman:
        name: rxvt-unicode, urxvt-perls, terminus-font
        state: latest
    - name: Copy 
      copy:
        src: dotfiles/.Xdefaults 
        dest: /home/tomswiggers/.Xdefaults
        owner: tomswiggers
        group: tomswiggers
    - name: mkdir
      file:
        path: /home/tomswiggers/.urxvt/ext
        state: directory    
        owner: tomswiggers
        group: tomswiggers
    - name: Copy 
      copy:
        src: dotfiles/.urxvt/ext/font-size 
        dest: /home/tomswiggers/.urxvt/ext/font-size
    

